import React from 'react';
import { AbsoluteFill, Audio, Sequence, interpolate, spring, staticFile, useCurrentFrame } from 'remotion';
import { appleMoreTimeline } from './AppleMoreTimeline';

const fps = 30;
const C = { ink: '#4d3429', cream: '#fff8e8', sky: '#a6ddf1', grass: '#79bd68', rail: '#a76b3e', red: '#e85e4f', redDark: '#9d4038', yellow: '#f5c74b', teal: '#68b7aa', blue: '#6ea9df', pink: '#ef9c9c' };
type Scene = 'opening' | 'left' | 'right' | 'ask' | 'answer' | 'rearrange' | 'equal' | 'closing';
// 音频分句之间可能有短暂间隔；间隔期间保持上一幕，不能回退到最后一幕。
const currentScene = (t: number) => {
  const active = appleMoreTimeline.segments.find((s) => t >= s.start && t < s.start + s.duration);
  if (active) return active;
  const previous = [...appleMoreTimeline.segments].reverse().find((s) => t >= s.start);
  return previous ?? appleMoreTimeline.segments[0];
};

const Cloud: React.FC<{ x: number; y: number; scale?: number }> = ({ x, y, scale = 1 }) => <div style={{ position: 'absolute', left: x, top: y, transform: `scale(${scale})`, transformOrigin: 'left top', opacity: .9 }}><div style={{ width: 210, height: 62, borderRadius: 60, background: '#fff' }}><i style={{ position: 'absolute', left: 35, top: -36, width: 92, height: 92, borderRadius: '50%', background: '#fff' }} /><i style={{ position: 'absolute', left: 108, top: -25, width: 78, height: 78, borderRadius: '50%', background: '#fff' }} /></div></div>;
const Flag: React.FC<{ x: number; y: number; color: string; flip?: boolean }> = ({ x, y, color, flip = false }) => <div style={{ position: 'absolute', left: x, top: y, width: 8, height: 230, background: '#7d5a45', transform: `rotate(${flip ? -6 : 6}deg)`, zIndex: 4 }}><div style={{ position: 'absolute', left: flip ? -5 : 5, top: 12, width: 80, height: 58, background: color, clipPath: 'polygon(0 0, 100% 0, 78% 50%, 100% 100%, 0 100%)' }} /></div>;
const Basket: React.FC<{ x: number; y: number; color?: string }> = ({ x, y, color = '#d39352' }) => <div style={{ position: 'absolute', left: x, top: y, width: 150, height: 110, borderRadius: '20px 20px 42px 42px', background: color, border: '7px solid #7b4b32', zIndex: 7, boxShadow: '0 9px 0 rgba(95,51,28,.16)' }}><div style={{ position: 'absolute', left: 22, top: -62, width: 94, height: 78, border: '10px solid #7b4b32', borderBottom: 0, borderRadius: 90 }} /></div>;
const Train: React.FC<{ x: number; y: number; color: string; label: string; wiggle?: number }> = ({ x, y, color, label, wiggle = 0 }) => <div style={{ position: 'absolute', left: x, top: y + wiggle, width: 430, height: 210, zIndex: 8 }}><div style={{ position: 'absolute', left: 0, top: 24, width: 360, height: 135, borderRadius: 28, background: color, border: '8px solid #75452e', boxShadow: '0 10px 0 rgba(90,50,32,.18)' }}><div style={{ position: 'absolute', left: 28, top: 25, width: 92, height: 65, borderRadius: 16, background: '#d9f2f0', border: '6px solid #75452e' }} /><div style={{ position: 'absolute', left: 145, top: 25, width: 92, height: 65, borderRadius: 16, background: '#d9f2f0', border: '6px solid #75452e' }} /><div style={{ position: 'absolute', left: 38, top: 91, minWidth: 160, height: 34, padding: '2px 12px', borderRadius: 12, background: 'rgba(255,248,232,.94)', border: '3px solid #9b633a', color: '#75452e', fontWeight: 900, fontSize: 24, lineHeight: '28px', textAlign: 'center', zIndex: 2 }}>{label}</div></div><div style={{ position: 'absolute', left: 344, top: 50, width: 90, height: 110, borderRadius: '20px 42px 42px 20px', background: color, border: '8px solid #75452e' }} /><div style={{ position: 'absolute', left: 55, top: 142, width: 54, height: 54, borderRadius: '50%', background: '#574138', border: '8px solid #d5a066' }} /><div style={{ position: 'absolute', left: 245, top: 142, width: 54, height: 54, borderRadius: '50%', background: '#574138', border: '8px solid #d5a066' }} /></div>;
const Apple: React.FC<{ x: number; y: number; active?: boolean; visible?: boolean; scale?: number; bob?: number; sad?: boolean }> = ({ x, y, active = false, visible = true, scale = 1, bob = 0, sad = false }) => <div style={{ position: 'absolute', left: x, top: y + bob, width: 104 * scale, height: 120 * scale, opacity: visible ? 1 : 0, transform: `scale(${scale})`, transformOrigin: 'bottom center', zIndex: 15, filter: active ? 'drop-shadow(0 0 16px #ffe36c)' : 'none' }}><div style={{ position: 'absolute', left: 8, top: 18, width: 88, height: 88, borderRadius: '48% 48% 58% 58%', background: C.red, border: `6px solid ${active ? '#ffd65f' : C.redDark}`, boxShadow: 'inset 12px 8px 0 rgba(255,255,255,.2)' }} /><div style={{ position: 'absolute', left: 46, top: 0, width: 13, height: 32, borderRadius: 10, background: '#744b2f', transform: 'rotate(8deg)' }} /><i style={{ position: 'absolute', left: 53, top: 1, width: 34, height: 18, borderRadius: '90% 10%', background: '#6fa956', transform: 'rotate(-18deg)' }} /><div style={{ position: 'absolute', left: 31, top: 52, width: 11, height: 16, borderRadius: '50%', background: '#4d3029' }} /><div style={{ position: 'absolute', left: 65, top: 52, width: 11, height: 16, borderRadius: '50%', background: '#4d3029' }} /><div style={{ position: 'absolute', left: 49, top: sad ? 75 : 76, width: 13, height: 10, borderRadius: sad ? '50% 50% 0 0' : '50%', borderTop: sad ? '4px solid #8d3d35' : '0', background: sad ? 'transparent' : '#f59a86' }} /><div style={{ position: 'absolute', left: -6, top: 70, width: 28, height: 14, borderRadius: 14, background: C.red, border: '4px solid #8e3d36', transform: 'rotate(18deg)' }} /><div style={{ position: 'absolute', right: -6, top: 70, width: 28, height: 14, borderRadius: 14, background: C.red, border: '4px solid #8e3d36', transform: 'rotate(-18deg)' }} /></div>;
const Sticker: React.FC<{ text: string; x: number; y: number; color: string }> = ({ text, x, y, color }) => <div style={{ position: 'absolute', left: x, top: y, padding: '12px 22px', borderRadius: 24, background: color, color: '#fff9e8', border: '5px solid #74452f', fontSize: 34, fontWeight: 900, zIndex: 25, boxShadow: '0 7px 0 rgba(79,47,30,.15)', transform: 'rotate(-2deg)' }}>{text}</div>;
const PairBridge: React.FC<{ x: number; y: number; width?: number }> = ({ x, y, width = 445 }) => <div style={{ position: 'absolute', left: x, top: y, width, height: 74, borderRadius: 42, background: 'rgba(255,239,177,.58)', border: '6px solid #edbf61', boxShadow: '0 7px 0 rgba(176,112,48,.12)', zIndex: 12 }}><div style={{ position: 'absolute', left: '50%', top: 27, width: 28, height: 18, marginLeft: -14, borderRadius: 18, background: '#fff7d4', border: '4px solid #d99a58' }} /></div>;
const EqualPairRow: React.FC<{ y: number; frame: number; index: number }> = ({ y, frame, index }) => <><div style={{ position: 'absolute', left: 250, top: y + 58, width: 500, height: 34, borderRadius: 20, background: '#fff0b4', border: '5px solid #edbf61', zIndex: 12 }}><div style={{ position: 'absolute', left: '50%', top: 5, width: 22, height: 16, marginLeft: -11, borderRadius: 16, background: '#fff8d7', border: '3px solid #d99a58' }} /></div><Apple x={145} y={y} bob={Math.sin((frame + index * 12) / 6) * 5} /><Apple x={700} y={y} bob={Math.sin((frame + index * 12) / 6) * 5} /></>;
const MiddleTeachingPanel: React.FC = () => <div style={{ position: 'absolute', left: 42, top: 360, width: 996, height: 920, borderRadius: 52, background: '#e9f7b7', border: '8px solid #5d9b43', boxShadow: '0 12px 0 rgba(75,125,55,.16)', zIndex: 1 }}><div style={{ position: 'absolute', inset: 32, borderRadius: 38, border: '5px solid #8abc60', opacity: .9 }} />{[120, 250, 380, 510, 640, 770].map((y) => <div key={y} style={{ position: 'absolute', left: 68, right: 68, top: y, height: 6, borderRadius: 6, background: '#d29a5c', opacity: .75 }} />)}</div>;
const Caption: React.FC<{ text: string }> = ({ text }) => <div style={{ position: 'absolute', left: 58, right: 58, bottom: 48, minHeight: 220, borderRadius: 34, background: 'rgba(255,249,232,.98)', border: '7px solid #e78736', display: 'flex', alignItems: 'center', justifyContent: 'center', textAlign: 'center', color: C.ink, fontWeight: 900, fontSize: 44, lineHeight: 1.18, padding: '24px 36px', zIndex: 40, boxShadow: '0 10px 0 rgba(129,80,42,.12)' }}>{text}</div>;

export const AppleTrainMore: React.FC = () => {
  const frame = useCurrentFrame();
  const t = frame / fps;
  const segment = currentScene(t);
  const scene = segment.scene as Scene;
  const local = Math.max(0, t - segment.start);
  const pulse = Math.sin(frame / 5) * 5;
  const trainMove = scene === 'opening' ? interpolate(local, [0, 3], [-500, 0], { extrapolateLeft: 'clamp', extrapolateRight: 'clamp' }) : 0;
  const reveal = (side: 'left' | 'right', i: number) => {
    if (scene === 'left' && side === 'left') return local > 1.05 + i * .85;
    if (scene === 'right' && side === 'right') return local > 1.05 + i * .7;
    return true;
  };
  const active = (side: 'left' | 'right', i: number) => (scene === 'left' && side === 'left' && local > 1.05 + i * .85 && local < 2.65 + i * .85) || (scene === 'right' && side === 'right' && local > 1.05 + i * .7 && local < 2.6 + i * .7);
  const apples = (side: 'left' | 'right', count: number, mode: 'train' | 'pair' | 'spread' | 'equal' = 'pair') => {
    const base = mode === 'spread'
      ? (side === 'left' ? 90 : 650)
      : (side === 'left' ? 145 : 565);
    const positions = mode === 'spread' && side === 'left' ? [[0, 805], [290, 805]] : mode === 'spread' && side === 'right' ? [[0, 840], [78, 840], [156, 840], [234, 840]] : mode === 'equal' ? [[0, 820], [120, 790], [240, 820]] : [[0, 820], [122, 820], [244, 820], [366, 820]];
    return positions.slice(0, count).map(([dx, y], i) => <Apple key={`${side}-${i}`} x={base + dx} y={y} visible={scene === 'left' || scene === 'right' ? reveal(side, i) : true} active={active(side, i) || (scene === 'answer' && side === 'right' && i > 1)} bob={(scene === 'equal' ? Math.sin((frame + i * 12) / 6) * 9 : Math.sin((frame + i * 8) / 10) * 3)} sad={scene === 'ask'} />);
  };
  const title = scene === 'opening' ? '孩子会数数，还不会比多少？' : scene === 'rearrange' ? '换个摆法，再看一次' : scene === 'equal' ? '两边一样多' : scene === 'closing' ? '家里也能这样玩' : '先数清楚，再看看哪边多';
  return <AbsoluteFill style={{ background: C.sky, fontFamily: 'Microsoft YaHei, PingFang SC, sans-serif', color: C.ink, overflow: 'hidden' }}>
    <div style={{ position: 'absolute', inset: 0, background: 'linear-gradient(#a6ddf1 0%, #c9edf5 46%, #8bc96f 47%, #63ad61 100%)' }} />
    <MiddleTeachingPanel />
    <Cloud x={45} y={150} scale={.8} /><Cloud x={770} y={190} scale={.68} /><Flag x={90} y={300} color={C.pink} /><Flag x={920} y={330} color={C.yellow} flip /><Basket x={30} y={600} /><Basket x={890} y={590} color="#8bc1dd" />
    <div style={{ position: 'absolute', left: 330, top: 295, width: 420, height: 120, borderRadius: 24, background: '#cf8d55', border: '8px solid #7d4e33', color: '#fff5de', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 52, fontWeight: 900, transform: 'rotate(-1deg)', zIndex: 7 }}>苹果小车站</div>
    <div style={{ position: 'absolute', left: 0, right: 0, top: 1030, height: 35, background: '#7a5238', zIndex: 3 }} /><div style={{ position: 'absolute', left: 0, right: 0, top: 1140, height: 24, background: '#7a5238', zIndex: 3 }} /><div style={{ position: 'absolute', left: 0, right: 0, top: 1090, height: 10, background: '#d9b378', zIndex: 3 }} />
    {[80, 270, 460, 650, 840, 1020].map((x) => <div key={x} style={{ position: 'absolute', left: x, top: 1000, width: 30, height: 200, background: '#c88754', border: '6px solid #774a32', borderRadius: 12, zIndex: 4 }} />)}
    <div style={{ position: 'absolute', left: 52, right: 52, top: 38, minHeight: 145, borderRadius: 34, background: 'rgba(255,249,232,.98)', border: '7px solid #df8736', display: 'flex', alignItems: 'center', justifyContent: 'center', textAlign: 'center', color: '#d56f2f', fontSize: scene === 'opening' ? 50 : 46, lineHeight: 1.16, fontWeight: 900, padding: '10px 24px', zIndex: 35 }}>{title}</div>

    {scene === 'opening' && <><div style={{ transform: `translateX(${trainMove}px)` }}><Train x={85} y={545} color={C.pink} label="左边小车" wiggle={pulse / 3} /><Train x={585} y={520} color={C.blue} label="右边小车" wiggle={-pulse / 3} />{[[155, 430], [278, 430]].map(([x, y], i) => <Apple key={`lt${i}`} x={x} y={y} scale={.82} bob={Math.sin((frame + i * 10) / 8) * 5} />)}{[[610, 405], [720, 405], [830, 405], [940, 405]].map(([x, y], i) => <Apple key={`rt${i}`} x={x} y={y} scale={.82} bob={Math.sin((frame + i * 9) / 8) * 5} />)}</div><Sticker text="先数清楚，再看看哪边多" x={260} y={735} color={C.teal} /></>}
    {scene === 'left' && <><Train x={-30} y={560} color={C.pink} label="左边小车" />{apples('left', 2)}{apples('right', 4, 'train') as any}<Sticker text="左边：2个" x={170} y={675} color={C.pink} /></>}
    {scene === 'right' && <><Train x={555} y={540} color={C.blue} label="右边小车" />{apples('left', 2, 'train') as any}{apples('right', 4)}<Sticker text="右边：4个" x={690} y={675} color={C.blue} /></>}
    {(scene === 'ask' || scene === 'answer') && <>{scene === 'answer' && <><PairBridge x={195} y={850} /><PairBridge x={317} y={850} /><div style={{ position: 'absolute', left: 770, top: 955, padding: '10px 18px', borderRadius: 22, background: '#ffe28a', border: '5px solid #9b633a', color: C.ink, fontSize: 30, fontWeight: 900, zIndex: 26 }}>多出来的两个</div></>}{apples('left', 2)}{apples('right', 4)}{scene === 'ask' && <div style={{ position: 'absolute', left: 460, top: 630, width: 160, height: 140, borderRadius: '50%', background: '#fff2be', border: '8px solid #9b633a', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 96, fontWeight: 900, zIndex: 28, transform: `scale(${1 + Math.sin(frame / 8) * .04})` }}>?</div>}{scene === 'answer' && <><Sticker text="右边更多" x={700} y={610} color={C.teal} /><Sticker text="左边更少" x={120} y={610} color={C.pink} /></>}</>}
    {scene === 'rearrange' && <>{apples('left', 2, 'spread')}{apples('right', 4, 'spread')}<Sticker text="左边摆得开" x={105} y={690} color={C.pink} /><Sticker text="右边摆得紧" x={735} y={690} color={C.blue} /></>}
    {scene === 'equal' && <><Sticker text="左边" x={100} y={610} color={C.pink} /><Sticker text="右边" x={760} y={610} color={C.blue} /><EqualPairRow y={700} frame={frame} index={0} /><EqualPairRow y={800} frame={frame} index={1} /><EqualPairRow y={900} frame={frame} index={2} /><Sticker text="每个都有一个伙伴" x={270} y={570} color={C.teal} /></>}
    {scene === 'closing' && <><Train x={300 + Math.sin(frame / 20) * 8} y={570} color={C.yellow} label="下一站：一起玩" /><div style={{ position: 'absolute', left: 130, top: 770, fontSize: 95 }}>🍎</div><div style={{ position: 'absolute', left: 330, top: 775, fontSize: 90 }}>🧱</div><div style={{ position: 'absolute', left: 520, top: 770, fontSize: 90 }}>🧸</div><div style={{ position: 'absolute', left: 710, top: 765, fontSize: 90 }}>🍌</div><div style={{ position: 'absolute', left: 120, top: 900, width: 840, borderRadius: 28, background: '#e4f2d8', border: '6px solid #6aa15b', padding: '22px 24px', textAlign: 'center', fontSize: 42, fontWeight: 900, zIndex: 22 }}>鞋子、水果、积木、玩具都能玩</div><Apple x={465} y={1010} scale={.95} bob={Math.sin(frame / 7) * 8} /></>}
    <Caption text={segment.caption} />
    {appleMoreTimeline.segments.filter((s) => s.id !== 'wait').map((s) => <Sequence key={s.id} from={Math.round(s.start * fps)}><Audio src={staticFile(`apple-more-lesson/${s.id}.mp3`)} /></Sequence>)}
  </AbsoluteFill>;
};
